### ISSUE TITLE
Link inválido

### ISSUE THREAD

**Issue by marquinhusgoncalves-zz** [bernarddeluna/oldRadio#7]
Bernard assisti sua talk Performance em CSS que você apresentou no BrazilJS 2012 e acabei descobrindo esse seu projeto porém o link para visualizar não abre mais, procurei e também não achei, como a talk é espetacular seria bacana ver esse projeto.

**Comment by zenorocha** [comment]
http://bernarddeluna.github.io/oldRadio/ ;)
